import json
import os
from datetime import datetime, timezone
from typing import List, Optional, Tuple

import yaml

from agentlab_cli.onboarding_doc import render_onboarding_md
from agentlab_cli.demo_harness_templates import DEMO_NODE_HARNESS, DEMO_PY_HARNESS
from agentlab_cli.typescript_wrapper_templates import (
    TS_WRAPPER_HARNESS,
    JS_WRAPPER_HARNESS,
    AGENTLAB_PACKAGE_JSON,
    AGENTLAB_CONFIG_JSON,
)


def _detect_command(repo_dir: str) -> Tuple[List[str], bool]:
    """Return (command, detected)."""
    candidates = [
        ("dist/cli.js", ["node", "./dist/cli.js", "run"]),
        ("harness/dist/cli.js", ["node", "./harness/dist/cli.js", "run"]),
        ("cli.py", ["python3", "./cli.py", "run"]),
        ("harness/cli.py", ["python3", "./harness/cli.py", "run"]),
    ]
    for rel, cmd in candidates:
        if os.path.exists(os.path.join(repo_dir, rel)):
            return cmd, True

    package_path = os.path.join(repo_dir, "package.json")
    if os.path.exists(package_path):
        try:
            with open(package_path, "r", encoding="utf-8") as f:
                pkg = json.load(f)
            bin_field = pkg.get("bin")
            if isinstance(bin_field, str):
                return ["node", bin_field], True
            if isinstance(bin_field, dict) and bin_field:
                key = sorted(bin_field.keys())[0]
                return ["node", bin_field[key]], True
        except Exception:
            pass

    return ["<set-your-harness-command>"], False


def _write_file(path: str, content: str, force: bool) -> None:
    if os.path.exists(path) and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def scaffold(
    repo_dir: str,
    experiment_path: str,
    tasks_path: str,
    manifest_path: str,
    command: Optional[List[str]] = None,
    integration_level: str = "cli_basic",
    step_semantics: str = "none",
    demo_harness: str = "none",
    typescript_wrapper: bool = False,
    force: bool = False,
) -> Tuple[List[str], List[str]]:
    os.makedirs(repo_dir, exist_ok=True)

    if demo_harness != "none":
        detected = True
        if demo_harness == "node":
            demo_path = os.path.join(repo_dir, "agentlab_demo_harness.js")
            _write_file(demo_path, DEMO_NODE_HARNESS, force)
            os.chmod(demo_path, 0o755)
            command = ["node", "./agentlab_demo_harness.js", "run"]
        elif demo_harness == "python":
            demo_path = os.path.join(repo_dir, "agentlab_demo_harness.py")
            _write_file(demo_path, DEMO_PY_HARNESS, force)
            os.chmod(demo_path, 0o755)
            command = ["python3", "./agentlab_demo_harness.py", "run"]
        else:
            raise ValueError("demo_harness must be one of: none, node, python")

    if command is None:
        command, detected = _detect_command(repo_dir)
    else:
        detected = True

    # DX: If this looks like a JS/TS repo and we couldn't detect a harness command,
    # automatically scaffold a wrapper so `lab run` works immediately.
    if (not typescript_wrapper) and (not detected) and os.path.exists(
        os.path.join(repo_dir, "package.json")
    ):
        typescript_wrapper = True

    if typescript_wrapper:
        agentlab_dir = os.path.join(repo_dir, "agentlab")
        os.makedirs(agentlab_dir, exist_ok=True)
        ts_path = os.path.join(agentlab_dir, "harness.ts")
        js_path = os.path.join(agentlab_dir, "harness.js")
        pkg_path = os.path.join(agentlab_dir, "package.json")
        cfg_path = os.path.join(agentlab_dir, "agentlab.config.json")
        _write_file(ts_path, TS_WRAPPER_HARNESS + "\n", force)
        _write_file(js_path, JS_WRAPPER_HARNESS + "\n", force)
        os.chmod(js_path, 0o755)
        _write_file(pkg_path, AGENTLAB_PACKAGE_JSON + "\n", force)
        _write_file(cfg_path, AGENTLAB_CONFIG_JSON + "\n", force)

        # Prefer runnable JS wrapper for immediate success.
        command = ["node", "./agentlab/harness.js", "run"]
        detected = True

    exp_id = f"exp_{datetime.now(timezone.utc).strftime('%Y_%m_%d')}_local"
    exp_name = os.path.basename(os.path.abspath(repo_dir)) or "agentlab_experiment"

    experiment = {
        "version": "0.3",
        "experiment": {
            "id": exp_id,
            "name": exp_name,
            "description": "Generated by lab init",
            "owner": "you",
            "tags": ["example"],
        },
        "dataset": {
            "suite_id": "local_suite",
            "provider": "local_jsonl",
            "path": os.path.relpath(tasks_path, repo_dir),
            "schema_version": "task_jsonl_v1",
            "split_id": "dev",
            "limit": 50,
        },
        "design": {
            "sanitization_profile": "hermetic_functional_v2",
            "comparison": "paired",
            "replications": 1,
            "random_seed": 1337,
            "shuffle_tasks": True,
            "max_concurrency": 1,
        },
        "analysis_plan": {
            "primary_metrics": ["success"],
            "secondary_metrics": ["latency_ms"],
            "missingness": {
                "policy": "paired_drop",
                "record_reasons": True,
            },
            "tests": {
                "success": {"method": "paired_bootstrap", "ci": 0.95, "resamples": 1000},
                "latency_ms": {"method": "paired_bootstrap", "ci": 0.95, "resamples": 1000},
            },
            "multiple_comparisons": {"method": "none"},
            "reporting": {
                "effect_sizes": ["risk_diff", "median_diff"],
                "show_task_level_table": True,
            },
        },
        "baseline": {
            "variant_id": "base",
            "bindings": {},
        },
        "variant_plan": [],
        "runtime": {
            "harness": {
                "mode": "cli",
                "command": command,
                "integration_level": integration_level,
                "input_path": "/out/trial_input.json",
                "output_path": "/out/trial_output.json",
                "control_plane": {"mode": "file", "path": "/state/lab_control.json"},
            },
            "network": {
                "mode": "none",
                "allowed_hosts": [],
            },
        },
        "validity": {
            "fail_on_state_leak": True,
            "fail_on_profile_invariant_violation": True,
        },
    }

    if integration_level in ("cli_events", "sdk_control", "sdk_full"):
        experiment["runtime"]["harness"]["events"] = {
            "mode": "jsonl",
            "path": "/out/harness_events.jsonl",
            "schema_version": "hook_events_v1",
        }

    if integration_level == "otel":
        experiment["runtime"]["harness"]["tracing"] = {
            "mode": "otlp",
            "otlp_endpoint": "http://127.0.0.1:4318",
        }

    tasks = [
        {"task_id": "t1", "input": {"prompt": "Summarize this paragraph."}},
        {"task_id": "t2", "input": {"prompt": "Translate to Spanish: Hello world."}},
    ]

    manifest = {
        "schema_version": "harness_manifest_v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "integration_level": integration_level,
        "harness": {
            "name": exp_name,
            "version": "0.1.0",
            "entry_command": command,
        },
        "step": {"semantics": step_semantics},
        "control_plane": {"mode": "file", "path": "/state/lab_control.json"},
    }

    if integration_level in ("cli_events", "sdk_control", "sdk_full"):
        manifest["hooks"] = {
            "schema_version": "hook_events_v1",
            "events_path": "/out/harness_events.jsonl",
            "header_event_emitted": False,
        }

    if integration_level == "otel":
        manifest["tracing"] = {"mode": "otlp", "otlp_endpoint": "http://127.0.0.1:4318"}

    experiment_yaml = yaml.safe_dump(experiment, sort_keys=False)
    tasks_jsonl = "\n".join(json.dumps(t) for t in tasks) + "\n"
    manifest_json = json.dumps(manifest, indent=2)

    created_files = [experiment_path, tasks_path, manifest_path]
    if typescript_wrapper:
        created_files.extend(
            [
                os.path.join(repo_dir, "agentlab", "harness.ts"),
                os.path.join(repo_dir, "agentlab", "harness.js"),
                os.path.join(repo_dir, "agentlab", "package.json"),
                os.path.join(repo_dir, "agentlab", "agentlab.config.json"),
            ]
        )
    onboarding_path = os.path.join(repo_dir, "AGENTLAB_ONBOARDING.md")
    created_files.append(onboarding_path)

    _write_file(experiment_path, experiment_yaml, force)
    _write_file(tasks_path, tasks_jsonl, force)
    _write_file(manifest_path, manifest_json, force)
    _write_file(
        onboarding_path,
        render_onboarding_md([os.path.basename(p) for p in created_files[:-1]]),
        force,
    )

    warnings = []
    if not detected:
        warnings.append("Harness command not detected; update runtime.harness.command")
    if typescript_wrapper and os.path.exists(os.path.join(repo_dir, "package.json")):
        warnings.append(
            "TypeScript wrapper scaffolded at agentlab/harness.js. Edit agentlab/agentlab.config.json to spawn your app."
        )

    return created_files, warnings
