from typing import List


def render_onboarding_md(created_files: List[str]) -> str:
    lines = []
    lines.append("# AgentLab Onboarding")
    lines.append("")
    lines.append("This repo was scaffolded with `lab init`.")
    lines.append("")
    lines.append("## What You Just Got")
    lines.append("")
    for f in created_files:
        lines.append(f"- `{f}`")
    lines.append("")
    lines.append("## Mental Model")
    lines.append("")
    lines.append("AgentLab runs a *harness* (your program) for each task/variant/replication.")
    lines.append("")
    lines.append("- The runner writes `trial_input.json` for a trial.")
    lines.append("- Your harness reads `trial_input.json` and writes `trial_output.json`.")
    lines.append("- AgentLab analyzes results and generates a report.")
    lines.append("")
    lines.append("```mermaid")
    lines.append("flowchart LR")
    lines.append("  A[tasks.jsonl] --> B[trial_input.json]")
    lines.append("  B --> C[Harness CLI]")
    lines.append("  C --> D[trial_output.json]")
    lines.append("  D --> E[analysis/]")
    lines.append("  E --> F[report/index.html]")
    lines.append("```")
    lines.append("")
    lines.append("In local (non-container) mode, the harness is executed with:")
    lines.append("")
    lines.append("- CWD set to the trial output directory (`.../.lab/runs/<run_id>/trials/<trial_id>/`).")
    lines.append("- Env vars:")
    lines.append("  - `AGENTLAB_TRIAL_INPUT` = absolute path to `trial_input.json`")
    lines.append("  - `AGENTLAB_TRIAL_OUTPUT` = absolute path to `trial_output.json`")
    lines.append("")
    lines.append("## `tasks.jsonl`")
    lines.append("")
    lines.append("`tasks.jsonl` is the dataset: one JSON object per line. The object is passed to the harness as `trial_input.task`.")
    lines.append("")
    lines.append("## `harness_manifest.json`")
    lines.append("")
    lines.append("This is *metadata about your harness* (integration level, step semantics, identity).")
    lines.append("In richer integration modes (`cli_events`, `otel`), the framework requires the harness to emit a `harness_manifest.json` per-trial (or copy a static one into the trial output directory).")
    lines.append("")
    lines.append("Start with `cli_basic` if you're just trying things out.")
    lines.append("")
    lines.append("## Fastest Success Path")
    lines.append("")
    lines.append("If you used `lab init --typescript-wrapper`, the generated harness wrapper already satisfies the contract.")
    lines.append("")
    lines.append("1. Run: `lab run experiment.yaml`")
    lines.append("2. Open: `.lab/runs/<run_id>/report/index.html`")
    lines.append("")
    lines.append("To wire this wrapper to *your* app, edit `agentlab/agentlab.config.json` and switch to `mode: \"spawn\"`.")
    lines.append("")
    lines.append("## How To Try")
    lines.append("")
    lines.append("1. Update `experiment.yaml` to point `runtime.harness.command` at your harness CLI (or re-run `lab init --demo-harness node`).")
    lines.append("2. Implement the harness to read `trial_input.json` and write `trial_output.json`.")
    lines.append("3. Run: `lab run experiment.yaml`")
    lines.append("4. Open: `.lab/runs/<run_id>/report/index.html`")
    lines.append("")
    return "\n".join(lines) + "\n"
